"""build number

Revision ID: 32809492b671
Revises: 53ac807fab89
Create Date: 2025-09-10 18:53:33.631424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32809492b671'
down_revision = '53ac807fab89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_version', schema=None) as batch_op:
        batch_op.drop_column('build_number')

    # ### end Alembic commands ###
