"""add is_superadmin to user

Revision ID: 5a8e9a480893
Revises: 9ba31335412d
Create Date: 2026-06-13 13:43:48.679899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8e9a480893'
down_revision = '9ba31335412d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_server_access', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_server_access', ['user_id', 'server_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('player_server_access', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_server_access', type_='unique')

    # ### end Alembic commands ###
