"""Plugin manager add on

Revision ID: 900887456f5d
Revises: efa3b1de57bc
Create Date: 2025-05-22 20:50:50.024101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900887456f5d'
down_revision = 'efa3b1de57bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('download_url', sa.String(length=255), nullable=True),
    sa.Column('plugin_type', sa.String(length=50), nullable=True),
    sa.Column('compatible_with', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('version_from', sa.String(length=50), nullable=True),
    sa.Column('version_to', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('config_path', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_plugins',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'plugin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_plugins')
    op.drop_table('plugin_config')
    op.drop_table('plugin_update_log')
    op.drop_table('plugin')
    # ### end Alembic commands ###
