"""add mod metadata fields0.2

Revision ID: 9ec655d6cecc
Revises: aba05e3f381c
Create Date: 2025-09-29 21:06:51.877797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec655d6cecc'
down_revision = 'aba05e3f381c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_be_plugin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('project_type')
        batch_op.drop_column('can_be_plugin')

    # ### end Alembic commands ###
