"""Add client_side and server_side columns to Mod

Revision ID: a99323ec55b1
Revises: 9ec655d6cecc
Create Date: 2025-10-27 14:06:51.799002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99323ec55b1'
down_revision = '9ec655d6cecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_side', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('server_side', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('server_side')
        batch_op.drop_column('client_side')

    # ### end Alembic commands ###
