"""add mod metadata fields

Revision ID: aba05e3f381c
Revises: 32809492b671
Create Date: 2025-09-29 19:22:42.735904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba05e3f381c'
down_revision = '32809492b671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minecraft_versions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supported_loaders', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('loader', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('minecraft_version', sa.String(length=20), nullable=True))
        batch_op.drop_column('compatible_with')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible_with', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('minecraft_version')
        batch_op.drop_column('loader')
        batch_op.drop_column('supported_loaders')
        batch_op.drop_column('minecraft_versions')

    # ### end Alembic commands ###
