"""Add source column to Plugin

Revision ID: d57f178792d9
Revises: 900887456f5d
Create Date: 2025-06-03 16:24:43.937640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57f178792d9'
down_revision = '900887456f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
